var alternative='As a alternative you can try to search on <a href="https://www.ar1web.co/" target="_blank" rel="nofollow">ar1web.co</a> and download it from there.</span><span><a href="">Please try to convert another YouTube video by clicking here</a>';
var progress=['starting','checking video','start download','downloading','start convert','converting'];
var e={
"insert":"Please insert video URL",
"selectoptions":"Please select options then click Start to convert video",
"wait":"Please wait another process finish",
"connectagain":"Try connect again",
"perip":"You have over max {var1} processing per IP. Please check <a href='javascript:void(0);' class='openhistory'>history page</a>.",
"param":"A parameter error occurred. The conversion was cancelled. Please delete your browser cache and try it again.",
"balance":"A balancer error occurred. The conversion was cancelled. Please refresh the page and try it again.",
"copyright":"The youtube video you try to convert is blacklisted due a DMCA request. Please try to convert another video.",
"copyright2":"We are sorry. Converting music videos from YouTube is not possible in your territory / region.",
"convert":"A conversion error occurred. The conversion was cancelled. Please refresh the page and try it again.",
"download":"A download error occurred. The conversion was cancelled. Please refresh the page and try it again.",
"restrict":"The video could not be downloaded because of the age restriction. We are not able to convert or download any videos with age restriction. Please try to convert another video.",
"duration":"We are sorry. The selected video is longer than 2 hours. We are only able to convert videos with a length up to 2 hours (120 minutes).",
"filesize":"We are sorry. The selected video is higher than 2GB. We are only able to convert videos with a size up to 2GB.",
"database":"A database error occurred. The conversion was cancelled. Please refresh the page and try it again.",
"server":"Server error. The conversion was cancelled. Please refresh the page and try it again.",
"connect":"Connect error. The conversion was cancelled. Please refresh the page and try it again.",
"longer":"We are sorry. The conversion was cancelled because longer 5 minutes. Please refresh the page and try it again.",
"higher":"We are sorry. The conversion was cancelled because selected dimension higher than video dimension. Please refresh the page and try it again.",
"novideo":"We are sorry. The conversion was cancelled because your link inserted has not video. Please refresh the page and try it again.",
"cutrange":"Cut time range incorrect. The conversion was cancelled. Please input correct range of time and try it again.",
}
var eshort={
"insert":"Please insert video URL",
"selectoptions":"Please select options then click Start to convert video",
"wait":"Please wait another process finish",
"connectagain":"Try connect again",
"perip":"Over max {var1} processing per IP.",
"param":"A parameter error occurred.",
"balance":"A balancer error occurred.",
"copyright":"The youtube video blacklisted due a DMCA request.",
"copyright2":"We are sorry. Converting music videos from YouTube is not possible in your territory / region.",
"convert":"A conversion error occurred.", 
"download":"A download error occurred.",
"restrict":"The video could not be downloaded because of the age restriction.",
"duration":"Video too long",
"filesize":"Video too big",
"database":"A database error occurred.",
"server":"Server error.",
"connect":"Connect error.",
"longer":"We are sorry.",
"higher":"We are sorry.",
"novideo":"We are sorry.",
"cutrange":"Cut time range incorrect.",
}
